name: diffasr
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - accelerate=1.8.1=pyhe01879c_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310hd8f1fbe_7
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cpython=3.10.18=py310hd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - filelock=3.18.0=pyhd8ed1ab_0
  - fsspec=2025.5.1=pyhd8ed1ab_0
  - gettext=0.19.8.1=h73d1719_1008
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py310h92f7908_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - hypothesis=6.136.0=pyha770c72_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jiwer=4.0.0=pyhe01879c_0
  - lame=3.100=h7f98852_1001
  - ld_impl_linux-64=2.40=h12ee557_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.3.4=h27087fc_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libogg=1.3.4=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=5.29.3=h3cdef7c_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtorch=2.6.0=cpu_mkl_h881e62d_106
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libxcb=1.17.0=h9b100fa_0
  - lz4-c=1.9.4=h6a678d5_1
  - mad=0.15.1b=h9c3ff4c_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.2.1=h9f54685_0
  - mpfr=4.1.0=h9202a9a_1
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - networkx=3.4.2=pyh267e887_2
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openssl=3.0.16=h5eee18b_0
  - opentelemetry-api=1.35.0=pyhd8ed1ab_0
  - packaging=25.0=pyh29332c3_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.22=pyh29332c3_1
  - pyctcdecode=0.5.0=pyhd8ed1ab_0
  - pygtrie=2.5.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.18=h1a3bd86_0
  - python_abi=3.10=2_cp310
  - rapidfuzz=3.12.1=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.4=pyhd8ed1ab_0
  - safetensors=0.5.3=py310h922eef2_0
  - setuptools=78.1.1=py310h06a4308_0
  - sleef=3.5.1=h9b69904_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h993c535_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.14.0=h32cad80_0
  - typing_extensions=4.14.0=pyhe01879c_0
  - wheel=0.45.1=py310h06a4308_0
  - wrapt=1.14.1=py310h5764c6d_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.23.0=py310h2c38b39_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.3.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.12
      - aiosignal==1.3.2
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - async-timeout==5.0.1
      - audioread==3.0.1
      - bitsandbytes==0.46.0
      - black==22.3.0
      - certifi==2025.4.26
      - cffi==1.17.1
      - cmake==4.0.3
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - cytoolz==1.0.1
      - datasets==3.6.0
      - decorator==5.2.1
      - dill==0.3.8
      - docopt==0.6.2
      - editdistance==0.8.1
      - einops==0.8.1
      - evaluate==0.4.4
      - fastapi==0.115.12
      - ffmpy==0.6.0
      - flake8==5.0.4
      - flashlight-text==0.0.7
      - flatbuffers==25.2.10
      - fonttools==4.58.4
      - frozenlist==1.7.0
      - gradio==3.23.0
      - graphviz==0.21
      - grpcio==1.73.1
      - h11==0.16.0
      - hf-xet==1.1.3
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.33.0
      - humanfriendly==10.0
      - intervaltree==3.1.0
      - isort==5.10.1
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      # - k2==1.24.4.dev20250714+cuda12.6.torch2.7.1
      - kaldi-decoder==0.2.7
      - kaldialign==0.9.2
      - kaldifst==1.7.14
      - kaldilm==1.15.2
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - lhotse==1.30.3
      - librosa==0.11.0
      - lilcom==1.8.1
      - linkify-it-py==2.0.3
      - lit==18.1.8
      - llvmlite==0.44.0
      - lxml==6.0.0
      - markdown==3.8.2
      - markdown-it-py==2.2.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mccabe==0.7.0
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - more-itertools==10.7.0
      - msgpack==1.1.1
      - multidict==6.4.4
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - narwhals==1.42.1
      - num2words==0.5.14
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.29.3
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.6.77
      - onnx==1.18.0
      - onnxconverter-common==1.13.0
      - onnxoptimizer==0.3.13
      - onnxruntime==1.22.0
      - onnxsim==0.4.36
      - openai-whisper==20250625
      - orjson==3.10.18
      - pandas==2.3.0
      - pathspec==0.12.1
      - peft==0.3.0
      - pillow==11.2.1
      - pip==25.1.1
      - platformdirs==4.3.8
      - pooch==1.8.2
      - portalocker==3.2.0
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - pyarrow==20.0.0
      - pycantonese==3.4.0
      - pycodestyle==2.9.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pyflakes==2.5.0
      - pygments==2.19.2
      - pylangacq==0.16.2
      - pyparsing==3.2.3
      - pypinyin==0.50.0
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - rich==14.0.0
      - rpds-py==0.25.1
      - sacrebleu==2.3.1
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - sox==1.5.0
      - soxr==0.5.0.post1
      - starlette==0.46.2
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.2
      - tomli==2.2.1
      - toolz==1.0.0
      - torch==2.7.1
      - torch-tb-profiler==0.4.3
      - torchaudio==2.7.1
      - transformers==4.53.2
      - triton==3.3.1
      - typeguard==4.4.4
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uc-micro-py==1.0.3
      - urllib3==2.4.0
      - uvicorn==0.34.3
      - wcwidth==0.2.13
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wordseg==0.0.2
      - xxhash==3.5.0
      - yarl==1.20.1
      - zhconv==1.4.3
